apiVersion : apps/v1
kind: Deployment
metadata:
  name: anjanamadushanctseassignment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anjanamadushanctseassignment
  template:
    metadata:
      labels:
        app: anjanamadushanctseassignment 
    spec:
      containers:
        - name: anjanamadushanctseassignment 
          image: ctseassign01.azurecr.io/anjanamadushanctseassignment
          ports:
          - containerPort: 5001